areas_dict = {
    "Antwerpen": [59518],
    "Barcelona": [347950],
    "Berlin": [62422],
    "Bern": [1686344],
    "Bordeaux": [1667452],
    "Bratislava": [1702499],
    "Brno": [438171],
    "Bruxelles": [2404020],
    "Bucharest": [377733],
    "Budapest": [37244],
    "Cardiff": [1625787],
    "Cologne": [62578],
    "Cork": [11797890],
    "Dijon": [1685958],
    "Dortmund": [1829065],
    "Dresden": [191645],
    "Dublin": [282800],
    "Düsseldorf": [62539],
    "Edinburgh": [1920901],
    "Frankfurt am Main": [62400],
    "Galway": [1390623],
    "Girona": [343535],
    "Glasgow": [1906767],
    "Gothenburg": [935611, 935463],
    "Helsinki": [38101],
    "Kyiv": [421866],
    "Lausanne": [6205453],
    "Liverpool": [172987],
    "Ljubljana": [1675898],
    "London": [175342],
    "Luxembourg": [407824],
    "Lyon": [1663048],
    "Madrid": [5326784],
    "Malmö": [10663667],
    "Marseille": [76469],
    "Milan": [44915],
    "Moscow": [2555133],
    "Munich": [3146373, 62428],
    "Nantes": [1658291],
    "Nicosia": [2628520],
    "Oslo": [406091],
    "Ostrava": [435509, 437640, 437592],
    "Padua": [44836],
    "Palma": [2174951],
    "Paris": [8649],
    "Poznań": [2989158],
    "Prague": [435514, 441584],
    "Riga": [1554509],
    "Seville": [342563],
    "Strasbourg": [4630050],
    "Szczecin": [404940],
    "Toulouse": [35738],
    "Trondheim": [10143487],
    "Turin": [44880],
    "Valencia": [344953],
    "Vienna": [109166],
    "Vilnius": [1529146],
    "Warszawa": [336075],
    "Wrocław": [2805691],
    "Zaragoza": [345740],
    "Zurich": [1690227]
}

countries_dict = {
    "Antwerpen": { "country": "Belgium", "code": "BE" },
    "Barcelona": { "country": "Spain", "code": "ES" },
    "Berlin": { "country": "Germany", "code": "DE" },
    "Bern": { "country": "Switzerland", "code": "CH" },
    "Bordeaux": { "country": "France", "code": "FR" },
    "Bratislava": { "country": "Slovakia", "code": "SK" },
    "Brno": { "country": "Czech Republic", "code": "CZ" },
    "Bruxelles": { "country": "Belgium", "code": "BE" },
    "Bucharest": { "country": "Romania", "code": "RO" },
    "Budapest": { "country": "Hungary", "code": "HU" },
    "Cardiff": { "country": "United Kingdom", "code": "UK" },
    "Cologne": { "country": "Germany", "code": "DE" },
    "Cork": { "country": "Ireland", "code": "IE" },
    "Dijon": { "country": "France", "code": "FR" },
    "Dortmund": { "country": "Germany", "code": "DE" },
    "Dresden": { "country": "Germany", "code": "DE" },
    "Dublin": { "country": "Ireland", "code": "IE" },
    "Düsseldorf": { "country": "Germany", "code": "DE" },
    "Edinburgh": { "country": "United Kingdom", "code": "UK" },
    "Frankfurt am Main": { "country": "Germany", "code": "DE" },
    "Galway": { "country": "Ireland", "code": "IE" },
    "Girona": { "country": "Spain", "code": "ES" },
    "Glasgow": { "country": "United Kingdom", "code": "UK" },
    "Gothenburg": { "country": "Sweden", "code": "SE" },
    "Helsinki": { "country": "Finland", "code": "FI" },
    "Kyiv": { "country": "Ukraine", "code": "UA" },
    "Lausanne": { "country": "Switzerland", "code": "CH" },
    "Liverpool": { "country": "United Kingdom", "code": "UK" },
    "Ljubljana": { "country": "Slovenia", "code": "SI" },
    "London": { "country": "United Kingdom", "code": "UK" },
    "Luxembourg": { "country": "Luxembourg", "code": "LU" },
    "Lyon": { "country": "France", "code": "FR" },
    "Madrid": { "country": "Spain", "code": "ES" },
    "Malmö": { "country": "Sweden", "code": "SE" },
    "Marseille": { "country": "France", "code": "FR" },
    "Milan": { "country": "Italy", "code": "IT" },
    "Moscow": { "country": "Russia", "code": "RU" },
    "Munich": { "country": "Germany", "code": "DE" },
    "Nantes": { "country": "France", "code": "FR" },
    "Nicosia": { "country": "Cyprus", "code": "CY" },
    "Oslo": { "country": "Norway", "code": "NO" },
    "Ostrava": { "country": "Czech Republic", "code": "CZ" },
    "Padua": { "country": "Italy", "code": "IT" },
    "Palma": { "country": "Spain", "code": "ES" },
    "Paris": { "country": "France", "code": "FR" },
    "Poznań": { "country": "Poland", "code": "PL" },
    "Prague": { "country": "Czech Republic", "code": "CZ" },
    "Riga": { "country": "Latvia", "code": "LV" },
    "Seville": { "country": "Spain", "code": "ES" },
    "Strasbourg": { "country": "France", "code": "FR" },
    "Szczecin": { "country": "Poland", "code": "PL" },
    "Toulouse": { "country": "France", "code": "FR" },
    "Trondheim": { "country": "Norway", "code": "NO" },
    "Turin": { "country": "Italy", "code": "IT" },
    "Valencia": { "country": "Spain", "code": "ES" },
    "Vienna": { "country": "Austria", "code": "AT" },
    "Vilnius": { "country": "Lithuania", "code": "LT" },
    "Warszawa": { "country": "Poland", "code": "PL" },
    "Wrocław": { "country": "Poland", "code": "PL" },
    "Zaragoza": { "country": "Spain", "code": "ES" },
    "Zurich": { "country": "Switzerland", "code": "CH" }
}

population_dict = {
    "Antwerpen": 523248,
    "Barcelona": { "country": "Spain", "code": "ES" },
    "Berlin": { "country": "Germany", "code": "DE" },
    "Bern": { "country": "Switzerland", "code": "CH" },
    "Bordeaux": { "country": "France", "code": "FR" },
    "Bratislava": { "country": "Slovakia", "code": "SK" },
    "Brno": { "country": "Czech Republic", "code": "CZ" },
    "Bruxelles": { "country": "Belgium", "code": "BE" },
    "Bucharest": { "country": "Romania", "code": "RO" },
    "Budapest": { "country": "Hungary", "code": "HU" },
    "Cardiff": { "country": "United Kingdom", "code": "UK" },
    "Cologne": { "country": "Germany", "code": "DE" },
    "Cork": { "country": "Ireland", "code": "IE" },
    "Dijon": { "country": "France", "code": "FR" },
    "Dortmund": { "country": "Germany", "code": "DE" },
    "Dresden": { "country": "Germany", "code": "DE" },
    "Dublin": { "country": "Ireland", "code": "IE" },
    "Düsseldorf": { "country": "Germany", "code": "DE" },
    "Edinburgh": { "country": "United Kingdom", "code": "UK" },
    "Frankfurt am Main": { "country": "Germany", "code": "DE" },
    "Galway": { "country": "Ireland", "code": "IE" },
    "Girona": { "country": "Spain", "code": "ES" },
    "Glasgow": { "country": "United Kingdom", "code": "UK" },
    "Gothenburg": { "country": "Sweden", "code": "SE" },
    "Helsinki": { "country": "Finland", "code": "FI" },
    "Kyiv": { "country": "Ukraine", "code": "UA" },
    "Lausanne": { "country": "Switzerland", "code": "CH" },
    "Liverpool": { "country": "United Kingdom", "code": "UK" },
    "Ljubljana": { "country": "Slovenia", "code": "SI" },
    "London": { "country": "United Kingdom", "code": "UK" },
    "Luxembourg": { "country": "Luxembourg", "code": "LU" },
    "Lyon": { "country": "France", "code": "FR" },
    "Madrid": { "country": "Spain", "code": "ES" },
    "Malmö": { "country": "Sweden", "code": "SE" },
    "Marseille": { "country": "France", "code": "FR" },
    "Milan": { "country": "Italy", "code": "IT" },
    "Moscow": { "country": "Russia", "code": "RU" },
    "Munich": { "country": "Germany", "code": "DE" },
    "Nantes": { "country": "France", "code": "FR" },
    "Nicosia": { "country": "Cyprus", "code": "CY" },
    "Oslo": { "country": "Norway", "code": "NO" },
    "Ostrava": { "country": "Czech Republic", "code": "CZ" },
    "Padua": { "country": "Italy", "code": "IT" },
    "Palma": { "country": "Spain", "code": "ES" },
    "Paris": { "country": "France", "code": "FR" },
    "Poznań": { "country": "Poland", "code": "PL" },
    "Prague": { "country": "Czech Republic", "code": "CZ" },
    "Riga": { "country": "Latvia", "code": "LV" },
    "Seville": { "country": "Spain", "code": "ES" },
    "Strasbourg": { "country": "France", "code": "FR" },
    "Szczecin": { "country": "Poland", "code": "PL" },
    "Toulouse": { "country": "France", "code": "FR" },
    "Trondheim": { "country": "Norway", "code": "NO" },
    "Turin": { "country": "Italy", "code": "IT" },
    "Valencia": { "country": "Spain", "code": "ES" },
    "Vienna": { "country": "Austria", "code": "AT" },
    "Vilnius": { "country": "Lithuania", "code": "LT" },
    "Warszawa": { "country": "Poland", "code": "PL" },
    "Wrocław": { "country": "Poland", "code": "PL" },
    "Zaragoza": { "country": "Spain", "code": "ES" },
    "Zurich": { "country": "Switzerland", "code": "CH" }
}